#!/bin/bash

# ----------------------------------------------------------------------------- #
# Script Name:   docker-installation
# Description:   This script install docker from scratch
# Written by:    Emiliano Monteverdi
# ----------------------------------------------------------------------------- #

echo "---> Uninstall older versions of docker <---"
sudo apt-get remove docker docker-engine docker.io containerd runc -y

sudo apt update

sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common -y

echo "---> Download docker <---"
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable" -y

sudo apt-get update

echo "---> Install docker <---"
sudo apt-get install docker-ce docker-ce-cli containerd.io -y

echo "---> Test docker installation <---"
sudo docker run hello-world
