#!/bin/bash

# KUBECTL
sudo apt-get update && sudo apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update

echo ---> KUBERNETES <---
sudo apt-get install -y kubectl

# MINIKUBE
echo ---> MINIKUBE <---
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && chmod +x minikube
sudo mkdir -p /usr/local/bin/
sudo install minikube /usr/local/bin/

echo ---> test minikube  <---
minikube start --vm-driver=none

echo ---> displays cluster info <---
kubectl cluster-info
