#!/bin/bash

# SPOTIFY
sudo apt install curl
curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list

# VISUAL STUDIO CODE
sudo apt install software-properties-common apt-transport-https wget
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

# CHROME
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

sudo apt-get update 

# SOFTWARE
echo -e "\n-----> SPOTIFY <-----\n"
sudo apt-get install spotify-client -y
echo -e "\n-----> GOOGLE CHROME <-----\n"
sudo dpkg -i google-chrome-stable_current_amd64.deb
echo -e "\n-----> VISUAL CODE <-----\n"
sudo apt install code -y
echo -e "\n-----> VIM <-----\n"
sudo apt install vim -y
echo -e "\n-----> HTOP <-----\n"
sudo apt install htop -y
echo -e "\n-----> GIT <-----\n"
sudo apt install git -y

# SNAP
echo -e "\n-----> SNAP <-----\n"
sudo apt install snap -y
echo -e "\n-----> DISCORD <-----\n"
sudo snap install discord
