#!/bin/bash

# ----------------------------------------------------------------------------- #
# Script Name:   github-ssh
# Description:   This script let you create or use an actual ssh key for github
# Written by:    Emiliano Monteverdi
# ----------------------------------------------------------------------------- #

if [ -f /home/$USER/.ssh/id_rsa ]; then

	echo -e "\n---> Adding your SSH key to the ssh-agent <---\n"
	eval "$(ssh-agent -s)"
	ssh-add /home/$USER/.ssh/id_rsa
else
	
	echo -e "\n---> Generating a new SSH key <---\n"
	echo -e "\nEnter github email\n"
	read email
	ssh-keygen -t rsa -b 4096 -C "$a"
	
        echo -e "\n---> Adding your SSH key to the ssh-agent <---\n"
        eval "$(ssh-agent -s)"
        ssh-add /home/$USER/.ssh/id_rsa
fi

echo -e "\n---> Copy the SSH key to clipboard <---\n"
sudo apt-get install xclip
xclip -sel clip < ~/.ssh/id_rsa.pub

echo -e "\n---> Proceed on https://github.com/settings/keys <---\n"

read -rsp $'\nPress any key to continue...\n' -n1 key

echo -e "\n---> Test your SSH connection <---\n"
ssh -T git@github.com

echo -e "\n---> Remember to clone your repos with the "Use SSH" option <---\n"
