#!/bin/bash
# ------------------------------------------------------------------------ #
# Script Name:   Github-SSH
# Description:   .
# Written by:    Emiliano Monteverdi
# ------------------------------------------------------------------------ #

echo "GitHub"
if [ -f /home/$USER/.ssh/id_rsa ]; then

	echo "---> Adding your SSH key to the ssh-agent <---"
	eval "$(ssh-agent -s)"
	ssh-add /home/$USER/.ssh/id_rsa
else
	
	echo "---> Generating a new SSH key <---"
	echo "Enter github email"
	read email
	ssh-keygen -t rsa -b 4096 -C "$a"
	
        echo "---> Adding your SSH key to the ssh-agent <---"
        eval "$(ssh-agent -s)"
        ssh-add /home/$USER/.ssh/id_rsa
fi

echo "---> Copy the SSH key to clipboard <---"
sudo apt-get install xclip
xclip -sel clip < ~/.ssh/id_rsa.pub

echo "---> Proceed on https://github.com/settings/keys <---"
