#!/bin/bash

# ----------------------------------------------------------------------------- #
# Script Name:   github-ssh
# Description:   This script let you create or use an actual ssh key for github
# Written by:    Emiliano Monteverdi
# ----------------------------------------------------------------------------- #

if [ -f /home/$USER/.ssh/id_rsa ]; then

	echo "---> Adding your SSH key to the ssh-agent <---"
	eval "$(ssh-agent -s)"
	ssh-add /home/$USER/.ssh/id_rsa
else
	
	echo "---> Generating a new SSH key <---"
	echo "Enter github email"
	read email
	ssh-keygen -t rsa -b 4096 -C "$a"
	
        echo "---> Adding your SSH key to the ssh-agent <---"
        eval "$(ssh-agent -s)"
        ssh-add /home/$USER/.ssh/id_rsa
fi

echo "---> Copy the SSH key to clipboard <---"
sudo apt-get install xclip
xclip -sel clip < ~/.ssh/id_rsa.pub

echo "---> Proceed on https://github.com/settings/keys <---"

read -rsp $'Press any key to continue...\n' -n1 key

echo "---> Test your SSH connection <---"
ssh -T git@github.com

echo "---> Remember to clone your repos with the "Use SSH" option <---"
